language: node_js
node_js:
  - "8.9.4"
 
script:
  - npm run test
env:
  - NODE_ENV=test
 
install:
  - npm install

services:
  - postgresql

before_script:
  - createdb test --username=postgres
  - sequelize db:migrate