language: node_js
install:
  - npm install -g sequelize-cli
  - npm install
node_js:
  - "stable"
script:
  - npm test
cache: 
  - npm install
  - npm install bcrypt@1.0.3
after_success:
  - travis_wait npm run coveralls
env:
  - NODE_ENV=test