language: node_js
node_js:
  - "8.9.4"
 
script:
  - npm run test
env:
  - NODE_ENV=test
  global:
  - PGPORT=5436
 
install:
  - npm install

services:
  - postgresql

before_script:
  - createdb test --username=postgres --password=k.code1234
  - npm run build
  - node_modules/.bin/sequelize db:migrate
  after_success:
  - npm run report-coverage
# after_success: npm run coverage
