language: node_js
node_js:
  - "node"
  - "8"
  deploy:
  skip_cleanup: true
  env:
- DB=postgres
matrix:
  fast_finish: true
  include:
  - node_js: 8
  env: KEY=VALUE
  allow_failures:
  - node_js: 8
  env: KEY=VALUE