language: node_js
install:
  - npm install
node_js:
  - "stable"
cache:
 directories:
  - node_modules
env:
  - NODE_ENV=test
script:
    - npm test
before_script:
  - createdb test --username=postgres
  - sequelize db:migrate 
after_success:
  - npm run test:coverage
