language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
- NODE_ENV=test
before_script:
- psql -c 'create database test;' -U postgres
- psql -c "CREATE USER root WITH PASSWORD 'k.code1234';" -U postgres
- npm run build
- npm run test-migrate
script: npm test
after_success: npm run coverage
# after_success: npm run coverage