language: node_js
node_js:
  - "8.9.4"
 
script:
  - npm run test
env:
  - NODE_ENV=test
  global:
  - PGPORT=5433
 
install:
  - npm install

services:
  - postgresql

before_script:
  - createdb travis --username=postgres
  - npm run "test-migrate"
  after_success:
  - npm run report-coverage