language: node_js
install:
  - npm install -g sequelize-cli
  - npm install
node_js:
    - "8.9.4"
cache:
 directories:
  - node_modules
script:
  - npm run test
after_success:
  - npm run test:coverage
env:
  - NODE_ENV=test